config/routes.rb
Rails.application.routes.draw do
 
 # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
 
 scope module: :public do
    root to: 'homes#top'
    get 'home/about' => 'home#about', as: 'about'
    get 'items/top' => 'items#top', as: 'top'
    resources :items, only: [:index, :show]
   
    get 'custmers/show' => 'customers#show', as: 'show' 
    get 'custmers/edit' => 'customers#edit', as: 'edit'
    get 'custmers/confirm' => 'customers#confirm', as: 'confirm'
    patch 'customers/update' => 'customers#update', as: 'update'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    
     
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    
    post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
    get 'orders/done' => 'orders#done', as: 'done'
    resources :orders, only: [:new, :create, :index, :show]
    
    
    
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
 end 
  # 管理者用
  # URL /admin
 
   namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    resources :genres, only: [:new, :index, :create, :edit, :update]
    resources :customers, only: [:new, :index, :show, :edit, :update]
    resources :orders, only: [:new, :index, :show, :update]
    resources :orders_details, only: [:new, :update]
  end  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    def address_display
        '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
    def subtotal
        item.with_tax_price * amount
    end
    
    def sum_of_price
        item.with_tax_price * amount
    end  
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    has_many :order_items, dependent: :destroy
    
    def get_image
        unless image.attached?
            file_path = Rails.root.join('app/assets/images/no.image.jpg')
            image.attach(io: File.open(file_path), filename: 'no.image.jpg', content_type: 'image/jpeg')
        end
        image
    end    
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_way: { credit_card: 0, transfer: 1 }
    has_many :order_dateils, dependent: :destroy
    belongs_to :customer
    has_many :items, through: :order_dateils
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order_dateil.rb
class OrderDateil < ApplicationRecord
    belongs_to :order
    belongs_to :item
    
    def subtotal
        item.with_tax_price * amount
    end
    
    def sum_of_price
        item.with_tax_price * amount
    end  
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    def index
        @customers = Customer.all
    end 
    
    def show
        @customer = Customer.find(params[:id])
    end
    
    def edit
        @customer = Customer.find(params[:id])
    end
    
    def update
        @customer = Customer.find(params[:id])
        @customer.update(customer_params)
        redirect_to admin_customer_path(@customer.id)
    end
    
    private
    def customer_params
        params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_active)
    end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    def index
        @genres = Genre.all
        @genre = Genre.new
        #@genre = Genre.new(genre_param)
    end   
    
    def new
        @genre = Genre.new
    end    
    
    def create
        @genre = Genre.new(genre_params)
        #@genres = Genre.all
        if @genre.save
         redirect_to admin_genres_path
        end    
    end
    
    def edit
        @genre = Genre.find(params[:id])
    end
    
    def update
        @genre = Genre.find(params[:id])
        @genre.update(genre_params)
        redirect_to admin_genres_path
        #if @genre.saves
        #else
        #end  
    end
    
    
    private
    
    def genre_params
        params.require(:genre).permit(:name)
    end    
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    def top
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
        @items = Item.all
        @item = Item.new
        @genre = @item.genre
    end    
    
    def new
        @item = Item.new
    end 
    
    def create
        @item = Item.new(item_params)
        @item.save
        redirect_to admin_item_path(@item.id)
    end
    
    def show
        @item = Item.find(params[:id])
        @genre = @item.genre
        #genre_id = Genre.find_by(code: params[:production][:genre_id]).id
        #Production.show(production_params.merge(genre_id: genre_id))
    end
    
    def edit
        @item = Item.find(params[:id])
        @genre = @item.genre
    end
    
    def update
        @item = Item.find(params[:id])
        @item.update(item_params)
        redirect_to admin_item_path(@item.id)
    end
    
    private
    def item_params
        params.require(:item).permit(:image, :name, :introduction, :price, :is_active, :genre_id)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    def index
        @orders = Order.all
        @items = Item.all
    end    
    
    def show
        @order = Order.find(params[:id])
        @orders = Order.all
        @customer = @order.customer
    end
    
    
    
     private
    def order_params
        params.require(:order).permit(:customer_id, :address, :postal_code, :name, :amount, :status, :payment, :postage, :all_price)
    end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_details_helper.rb
module Admin::OrdersDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="h3 m-5 col-3 bg-info text-black text-center">
<%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集
</div>
<p>会員ID <%= @customer.id %></p>
<%= form_with model: @customer, url: admin_customer_path(@customer.id), url: admin_customer_path, method: :patch do |f| %>
    <p>氏名 : <%= f.text_field :last_name %><%= f.text_field :first_name %></p>
    <p>フリガナ : <%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></p>
    <p>郵便番号 : <%= f.text_field :postal_code %></p>
    <p>住所 : <%= f.text_field :address %></p>
    <p>電話番号 : <%= f.text_field :telephone_number %></p>
    <p>メールアドレス : <%= f.text_field :email %></p>
    <p>会員ステータス : <%= f.radio_button :is_active, "true" %>
                        <%= f.label :is_active, "有効" %>
        
                        <%= f.radio_button :is_active, "false" %>
                        <%= f.label :is_active, "退会" %>
    </p>
            
                <%= f.submit "変更を保存", class: "btn btn-success" %>
    
<% end %>            

app/views/admin/customers/index.html.erb
<div class="h3 m-5 col-3 bg-info text-black text-center">
  会員一覧
</div>
<table class="table table-hover table-inverse">
    <thead>
        <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
        </tr>
    </thead>
    <tbody>
        <% @customers.each do |customer| %>
        <tr>
            <td><%= customer.id %> </td>
            <td>
                <%= link_to admin_customer_path(customer.id) do %>
                    <%= customer.last_name %><%= customer.first_name %>
                <% end %>    
            </td>

            <td><%= customer.email %></td>
            <td>
                <% if customer.is_active %> 
                    <p>有効</p>
                <% else %> 
                    <p>退会</p>
                <% end %> 
            </td>
        <% end %>    
        </tr>
    </tbody>
</table>

app/views/admin/customers/show.html.erb
<div class="h3 m-5 col-3 bg-info text-black text-center">
  <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細
</div>

<table class="table table-borderless">
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
        </tr>
        <tr>
            <th>氏名</th>
            <td><%= @customer.last_name %><%= @customer.first_name %></td>
        </tr>
        <tr>
            <th>フリガナ</th>
            <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
        </tr>
        <tr>
            <th>郵便番号</th>
            <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
            <th>住所</th>
            <td><%= @customer.address %></td>
        </tr>
        <tr>
            <th>電話番号</th>
            <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
            <th>メールアドレス</th>
            <td><%= @customer.email %></td>
        </tr>
        <tr>
            <th>会員ステータス</th>
            <td>
                <% if @customer.is_active %> 
                    <p>有効</p>
                <% else %> 
                    <p>退会</p>
                <% end %> 
            </td>
        </tr>
    </tbody>
</table>
    
        <%= link_to edit_admin_customer_path(@customer) do %>
            <button type="button" class="btn btn-success">編集する</button>
        <% end %>
        

        <%= link_to admin_orders_path do %>
            <button type="button" class="btn btn-info">注文履歴一覧を見る</button>
        <% end %>
      