config/routes.rb
Rails.application.routes.draw do
 
 # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
 
 scope module: :public do
    root to: 'homes#top'
    get 'home/about' => 'home#about', as: 'about'
    get 'items/top' => 'items#top', as: 'top'
    resources :items, only: [:index, :show]
   
    get 'custmers/show' => 'customers#show', as: 'show' 
    get 'custmers/edit' => 'customers#edit', as: 'edit'
    get 'custmers/confirm' => 'customers#confirm', as: 'confirm'
    patch 'customers/update' => 'customers#update', as: 'update'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    
     
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    
    post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
    get 'orders/done' => 'orders#done', as: 'done'
    resources :orders, only: [:new, :create, :index, :show]
    
    
    
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
 end 
  # 管理者用
  # URL /admin
 
   namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    resources :genres, only: [:new, :index, :create, :edit, :update]
    resources :customers, only: [:new, :index, :show, :edit, :update]
    resources :orders, only: [:new, :index, :show, :update]
    resources :orders_details, only: [:new, :update]
  end  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_way: { credit_card: 0, transfer: 1 }
    has_many :order_dateils, dependent: :destroy
    belongs_to :customer
    has_many :items, through: :order_dateils
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    def index
        @orders = Order.all
        @items = Item.all
    end    
    
    def show
        @order = Order.find(params[:id])
        @orders = Order.all
        @customer = @order.customer
    end
    
    
    
     private
    def order_params
        params.require(:order).permit(:customer_id, :address, :postal_code, :name, :amount, :status, :payment, :postage, :all_price)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/confirm.html.erb
<div class="h3 d-inline bg-info text-black">
    注文情報確認
</div>

app/views/admin/orders/done.htme.erb
<div class="container">
    <div class="text-center">
        ご注文ありがとうございました！
    </div>
</div>

app/views/admin/orders/index.html.erb
<div class="h3 d-inline bg-info text-black">
  注文履歴一覧
</div>
        <table class="table table-hover table-inverse">
            <thead>
                <tr>
                    <th>購入日時</th>
                    <th>購入者</th>
                    <th>注文個数</th>
                    <th>注文ステータス</th>
                </tr>
            </thead>
            <tbody>
                <% @orders.each do |order| %>
                <tr>
                    <td>
                        <%= link_to admin_order_path(order.id) do %>
                            <%= order.created_at %>
                        <% end %>
                    </td>
                    <td><%= order.name %></td>
                    <td>
                        <% @sum=0 %>
                        <% order.order_dateils.each do |order_dateil| %>
                            <% @sum += order_dateil.amount %>
                        <% end %>
                        <%= @sum %>
                    </td>
                    <td></td>
                </tr>
                <% end %>
            </tbody>
        </table>

app/views/admin/orders/new.html.erb
<div class="h3 d-inline bg-info text-black">
    注文情報入力
</div>
<div class="row">
    <div class="col-2">
        支払方法
    </div>
</div>
<div class="row">
    <div class="col-3">
        <%= f.radio_button :payment_method, Order.payment_methods.key(0) %>
        <%= f.label :payment_method, Order.payment_methods_i18n[:credit_card] %>

        <%= f.radio_button :payment_method, Order.payment_methods.key(1) %>
        <%= f.label :payment_method, Order.payment_methods_i18n[:transfer]%>
    </div>
</div>
<div class="row">
    <div class="col-2">
        お届け
    </div>
</div>

app/views/admin/orders/show.html.erb
<div class="h3 m-5 col-3 bg-info text-black text-center">
  注文履歴
</div>
<h2>注文履歴詳細</h2>
<p>購入者 : 
    <%= link_to admin_customer_path(@customer.id) do %>
        <%= @order.name %>
    <% end %>    
</p>
<p>注文日 : <%= @order.created_at %></p>
<p>配送先 : <%= @order.address %></p>
<p>支払方法 : 
    <%= @order.payment_way_i18n %>
</p>
<p>注文ステータス :</p>


<table class="table table-hover table-inverse">
    <thead class="table-secondary">
        <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
            <th colspan="1"></th>
        </tr>
    </thead>
    <tbody>
        <% @order.order_dateils.each do |order_dateil| %>
        <tr>
            <td><%= order_dateil.item.name %></td>
            <td><%= order_dateil.item.with_tax_price.to_s(:delimited) %></td>
            <td><%= order_dateil.amount %></td>
            <td><%= order_dateil.item.with_tax_price * order_dateil.amount %></td>
        </tr>
        <% end %>
    </tbody>
</table>
    
<div class="container-fluid">
    <div class="row">
            <table class="table table-borderless">
                <thead></thead>
                <tbody>
                 
                     <tr>
                        <th>商品合計</th>
                        <td><%= @order.all_price-@order.postage %></td>
                    </tr>
                    <tr>
                        <th>配送料</th>
                        <td><%= @order.postage %></td>
                    </tr>
                    <tr>
                        <th>ご請求金額</th>
                        <td><%= @order.all_price %></td>
                    </tr>
                </tbody>    
            </table>
    </div>
</div>        