config/routes.rb
Rails.application.routes.draw do
 
 # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
 
 scope module: :public do
    root to: 'homes#top'
    get 'home/about' => 'home#about', as: 'about'
    get 'items/top' => 'items#top', as: 'top'
    resources :items, only: [:index, :show]
   
    get 'custmers/show' => 'customers#show', as: 'show' 
    get 'custmers/edit' => 'customers#edit', as: 'edit'
    get 'custmers/confirm' => 'customers#confirm', as: 'confirm'
    patch 'customers/update' => 'customers#update', as: 'update'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    
     
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    
    post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
    get 'orders/done' => 'orders#done', as: 'done'
    resources :orders, only: [:new, :create, :index, :show]
    
    
    
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
 end 
  # 管理者用
  # URL /admin
 
   namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    resources :genres, only: [:new, :index, :create, :edit, :update]
    resources :customers, only: [:new, :index, :show, :edit, :update]
    resources :orders, only: [:new, :index, :show, :update]
    resources :orders_details, only: [:new, :update]
  end  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    def address_display
        '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
    def subtotal
        item.with_tax_price * amount
    end
    
    def sum_of_price
        item.with_tax_price * amount
    end  
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    has_many :order_items, dependent: :destroy
    
    def get_image
        unless image.attached?
            file_path = Rails.root.join('app/assets/images/no.image.jpg')
            image.attach(io: File.open(file_path), filename: 'no.image.jpg', content_type: 'image/jpeg')
        end
        image
    end    
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_way: { credit_card: 0, transfer: 1 }
    has_many :order_dateils, dependent: :destroy
    belongs_to :customer
    has_many :items, through: :order_dateils
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order_dateil.rb
class OrderDateil < ApplicationRecord
    belongs_to :order
    belongs_to :item
    
    def subtotal
        item.with_tax_price * amount
    end
    
    def sum_of_price
        item.with_tax_price * amount
    end  
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    def index
        @genres = Genre.all
        @genre = Genre.new
        #@genre = Genre.new(genre_param)
    end   
    
    def new
        @genre = Genre.new
    end    
    
    def create
        @genre = Genre.new(genre_params)
        #@genres = Genre.all
        if @genre.save
         redirect_to admin_genres_path
        end    
    end
    
    def edit
        @genre = Genre.find(params[:id])
    end
    
    def update
        @genre = Genre.find(params[:id])
        @genre.update(genre_params)
        redirect_to admin_genres_path
        #if @genre.saves
        #else
        #end  
    end
    
    
    private
    
    def genre_params
        params.require(:genre).permit(:name)
    end    
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    def top
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
        @items = Item.all
        @item = Item.new
        @genre = @item.genre
    end    
    
    def new
        @item = Item.new
    end 
    
    def create
        @item = Item.new(item_params)
        @item.save
        redirect_to admin_item_path(@item.id)
    end
    
    def show
        @item = Item.find(params[:id])
        @genre = @item.genre
        #genre_id = Genre.find_by(code: params[:production][:genre_id]).id
        #Production.show(production_params.merge(genre_id: genre_id))
    end
    
    def edit
        @item = Item.find(params[:id])
        @genre = @item.genre
    end
    
    def update
        @item = Item.find(params[:id])
        @item.update(item_params)
        redirect_to admin_item_path(@item.id)
    end
    
    private
    def item_params
        params.require(:item).permit(:image, :name, :introduction, :price, :is_active, :genre_id)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    def index
        @orders = Order.all
        @items = Item.all
    end    
    
    def show
        @order = Order.find(params[:id])
        @orders = Order.all
        @customer = @order.customer
    end
    
    
    
     private
    def order_params
        params.require(:order).permit(:customer_id, :address, :postal_code, :name, :amount, :status, :payment, :postage, :all_price)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "こちら", new_session_path(resource_name) %>からログインしてください。
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkGithub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-right bg-warning">
        <div class="container">
          <%= link_to top_path do %>
            <h1>ながのCAKE!</h1>
          <% end %>  
          <div class="navbar-collapse collspace show" id="navbarNavDropdown" style>
            <ul class="nav justify-content-around">
              <% if admin_signed_in? %>
                <li>
                  <%= link_to admin_items_path do %>
                    <button type="button" class="btn btn-outline-info">商品一覧</button>
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_customers_path do %>
                    <button type="button" class="btn btn-outline-info">会員一覧</button>
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_orders_path do %>
                    <button type="button" class="btn btn-outline-info">注文履歴一覧</button>
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_genres_path do %>
                    <button type="button" class="btn btn-outline-info">ジャンル一覧</button>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_admin_session_path, method: :delete do %>
                    <button type="button" class="btn btn-outline-danger">ログアウト</button>
                  <% end %>
                </li>
          
              <% elsif customer_signed_in? %>
                <li>
                  <%= link_to show_path(current_customer.id) do %>
                    <button type="button" class="btn btn-outline-info">マイページ</button>
                  <% end %>
                </li>
                <li>
                  <%= link_to items_path do %>
                    <button type="button" class="btn btn-outline-info">商品一覧</button>
                  <% end %>  
                </li>
                <li>
                  <%= link_to cart_items_path do %>
                    <button type="button" class="btn btn-outline-info">カート</button>
                  <% end %>  
                </li>
                <li>
                  <%= link_to destroy_customer_session_path, method: :delete do %>
                    <button type="button" class="btn btn-outline-danger">ログアウト</button>
                  <% end %>  
                </li>
                
              <% else %>
                <li>
                  <%= link_to about_path do %>
                    <button type="button" class="btn btn-outline-info">About</button>
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_items_path do %>
                    <button type="button" class="btn btn-outline-info">商品一覧</button>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_customer_registration_path do %>
                    <button type="button" class="btn btn-outline-secondary">新規登録</button>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_customer_session_path do %>
                    <button type="button" class="btn btn-outline-success">ログイン</button>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>